FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
ENV NUGET_XMLDOC_MODE skip
WORKDIR /vsdbg
RUN apt-get update \
    && apt-get install -y nfs-common \
    && apt-get install -y cifs-utils \
    && apt-get install -y procps \
    && apt-get install -y --no-install-recommends \
        unzip \
    && rm -rf /var/lib/apt/lists/* \
    && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg
RUN mkdir /app
WORKDIR /app
COPY mount.sh /app
ENTRYPOINT ["tail", "-f", "/dev/null"]